### PR TITLE
Update sgv2-filter.user.js

### PR DESCRIPTION
**Pull request by silentguy256**
Add all relevant references to "https://www.steamgifts.com/". Left in all refs to "http://www.steamgifts.com/" in case site ever goes back.

### CODE REVIEW

**Comment by GarionCZ** [comment]
Hi, thanks for the submission! Could you also increase the version to 0.5.5-DEV in the same commit? Thanks.

**Comment by silentguy256** [comment]
Sure thing. Also added a fix for ppl that had problems with sg++ grid view. not that sg++ is working right now ;)

**Comment by GarionCZ** [comment]
Awesome, but could you separate those into two pull requests? I try to keep it one commit = one version so it's easy for outside people to know what's happening and automatic updates actually work for them. I'll try both changes in about 10 hours and merge them into beta/release.

**Comment by silentguy256** [comment]
Argh, now we are getting into confusing territory for me, never taken the time to really get into git, right now I'm just doing this the lazy way with the web interface... Might be easier if you just "merge" my edits by hand to be to your liking, essentially I just added a few s anyway ;)

**Comment by GarionCZ** [comment]
Nah, it's OK, I don't want to take the credit from you :) Gonna merge it as it is.

**Pull request merged**
